language: node_js
node_js:
  - "0.10"

env:
  global:
    - TEST=test

before_script:
  - echo 'before_script running...'
  - echo $TEST$

after_script:
  - echo 'after_script running...'
  - echo 'All done!'