// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('app').directive('caNumDisplay', function() {
    return {
      templateUrl: 'partials/ca-num-display.html',
      transclude: true,
      restrict: 'E',
      scope: {
        name: "@",
        type: "@",
        cur: "=",
        pre: "=",
        curBaseline: "=",
        preBaseline: "="
      },
      link: function(scope, ele, attrs) {
        scope.show = function(input, equality) {
          return !isNaN(parseFloat(input)) && isFinite(input) && Math.abs(input) > equality;
        };
        scope.diff = function(cur, pre, pct) {
          if (pct === true) {
            return (cur - pre) / pre * 100;
          } else {
            return cur - pre;
          }
        };
        scope.diffBaseline = function(input, baseline) {
          if ((input != null) && (baseline != null)) {
            return input - baseline;
          }
        };
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=app-dir.map
*/
