// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('app').filter('pct', function() {
    return function(input) {
      if (input !== 0) {
        return "" + (Math.round(input * 100)) + "%";
      }
    };
  });

  angular.module('app').filter('round', function() {
    return function(input, decimals) {
      return Math.round(input * Math.pow(10, decimals)) / Math.pow(10, decimals);
    };
  });

}).call(this);

/*
//@ sourceMappingURL=app-filter.map
*/
