// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('app').filter('pct', function() {
    return function(input) {
      if (input !== 0) {
        return "" + ((input * 1).toFixed(2)) + "%";
      }
    };
  });

  angular.module('app').filter('round', function() {
    return function(input) {
      return (input * 1).toFixed(2);
    };
  });

}).call(this);

/*
//@ sourceMappingURL=app-filter.map
*/
